---
- hosts: 172.31.15.241
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
       src:  mystatic
       dest: /home/ubuntu/mystaticfile

  - name:  i want to install webserver
    apt:
      name: apache2
      state: present 
  
  - name:  copy dynamic file into node side 
    template: 
      src: myindexfile.j2
      dest: /var/www/html/index.html
    notify: restartwebserver

  - name: download remote file
    get_url:
       url: https://abhi15june22.s3.us-west-2.amazonaws.com/mahaLogin.war
       dest: /home/ubuntu/mahaLogin.war
       force_basic_auth: yes
  handlers:
  - name: restartwebserver
    systemd:
       name: apache2
       state: restarted
  
