---
- hosts: 172.31.15.241
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
       src:  mystatic
       dest: /home/ubuntu/mystaticfile

  - name:  i want to install webserver
    apt:
      name: apache2
      state: present 
       

