---
- hosts: 172.31.15.241
  become: yes
  tasks:
  - name: i want execute mult package
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget 
    tags: mymultipack